// Action for Pet data
export const ADD_PET = "ADD_PET";
export const ADD_PET_SUCCESSFUL = "ADD_PET_SUCCESSFUL";
export const ADD_PET_ERROR = "ADD_PET_ERROR";
export const LOAD_USER_PETS = "LOAD_USER_PETS";
export const DELETE_PETS = "DELETE_PETS";
export const DELETE_PETS_SUCCESSFUL = "DELETE_PETS_SUCCESSFUL";

export const UPDATE_PET = "UPDATE_PET";
export const UPDATE_PET_SUCCESSFUL = "UPDATE_PET_SUCCESSFUL";
export const UPDATE_PET_ERROR = "UPDATE_PET_ERROR ";

export const GET_ALL_PET = "GET_ALL_PET";
export const GET_ALL_PET_SUCCESSFUL = "GET_ALL_PET_SUCCESSFUL";
export const GET_ALL_PET_ERROR = "GET_ALL_PET_ERROR";

export const GET_PET_BY_USER = "GET_PET_BY_USER";
export const GET_PET_BY_USER_SUCCESSFUL = "GET_PET_BY_USER_SUCCESSFUL";
export const GET_PET_BY_USER_ERROR = "GET_PET_BY_USER_ERROR";

export const GET_SINGLE_PET = "GET_SINGLE_PET";
export const GET_SINGLE_PET_SUCCESSFUL = "GET_SINGLE_PET_SUCCESSFUL";
export const GET_SINGLE_PET_ERROR = "GET_SINGLE_PET_ERROR";

//Action for Pet Types
export const GET_PET_TYPES = "GET_PET_TYPES";
export const GET_PET_TYPES_SUCCESSFUL = "GET_PET_TYPES_SUCCESSFUL";
export const GET_PET_TYPES_ERROR = "GET_PET_TYPES_ERROR";

//Action for Setting
export const SUPPORT_UPLOAD_SCREENSHOT = "SUPPORT_UPLOAD_SCREENSHOT";
export const SUPPORT_UPLOAD_SCREENSHOT_SUCCESSFUL =
  "SUPPORT_UPLOAD_SCREENSHOT_SUCCESSFUL";
export const SUPPORT_UPLOAD_SCREENSHOT_ERROR =
  "SUPPORT_UPLOAD_SCREENSHOT_ERROR";

//Update User Info for Setting page.
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESSFUL = "UPDATE_USER_SUCCESSFUL";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const STORE_PUSH_TOKEN = "STORE_PUSH_TOKEN";

export const USER_LOGOUT = "USER_LOGOUT";
export const USER_LOGOUT_SUCCESSFUL = "USER_LOGOUT_SUCCESSFUL";
export const USER_LOGOUT_ERROR = "USER_LOGOUT_ERROR";

//Action for Label.
export const ADD_LABEL = "ADD_LABEL";
export const UPDATE_LABEL = "UPDATE_LABEL";
export const LOAD_LABEL_DATA = "LOAD_LABEL_DATA";
export const DELETE_LABEL = "DELETE_LABEL";
export const GET_ALL_LABEL_BY_USER = "GET_ALL_LABEL_BY_USER";
export const GET_ALL_CUSTOM_DEFAULT_LABEL = "GET_ALL_CUSTOM_DEFAULT_LABEL";
export const LOAD_COMBINE_LABEL = "LOAD_COMBINE_LABEL";

//Action for show loader
export const SHOW_LOADER = "SHOW_LOADER";

//Action for show dialog
export const SHOW_DIALOG = "SHOW_DIALOG";
export const SET_DIALOG_TITLE = "SET_DIALOG_TITLE";
export const SET_DIALOG_CONTAIN = "SET_DIALOG_CONTAIN";
export const SET_DIALOG_FOOTER = "SET_DIALOG_FOOTER";

//Action for add reminder
export const ADD_REMINDER = "ADD_REMINDER";
export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const REMOVE_REMINDER = "REMOVE_REMINDER";
export const GET_REMINDER_BY_USER = "GET_REMINDER_BY_USER";
export const LOAD_REMINDER = "LOAD_REMINDER";
export const LOAD_REMINDER_TEMPLATE = "LOAD_REMINDER_TEMPLATE";
export const GET_REMINDER_BY_PET = "GET_REMINDER_BY_PET";
export const GET_REMINDER_TEMPLATE = "GET_REMINDER_TEMPLATE";
export const UPDATE_REMINDER_STATUS = "UPDATE_REMINDER_STATUS";

//Action for Tracker
export const ADD_TRACKER = "ADD_TRACKER";
export const ADD_TRACKER_SUCCESSFUL = "ADD_TRACKER_SUCCESSFUL";
export const ADD_TRACKER_ERROR = "ADD_TRACKER_ERROR";

export const UPDATE_TRACKER = "UPDATE_TRACKER";
export const UPDATE_TRACKER_SUCCESSFUL = "UPDATE_TRACKER_SUCCESSFUL";
export const UPDATE_TRACKER_ERROR = "UPDATE_TRACKER_ERROR";

export const GET_TRACKER_BY_USER = "GET_TRACKER_BY_USER";
export const GET_TRACKER_BY_USER_SUCCESSFUL = "GET_TRACKER_BY_USER_SUCCESSFUL";
export const GET_TRACKER_BY_USER_ERROR = "GET_TRACKER_BY_USER_ERROR";

export const GET_TRACKER_BY_PET = "GET_TRACKER_BY_PET";
export const GET_TRACKER_BY_PET_SUCCESSFUL = "GET_TRACKER_BY_PET_SUCCESSFUL";
export const GET_TRACKER_BY_PET_ERROR = "GET_TRACKER_BY_PET_ERROR";

export const GET_TRACKER_BY_ID = "GET_TRACKER_BY_ID";
export const GET_TRACKER_BY_ID_SUCCESSFUL = "GET_TRACKER_BY_ID_SUCCESSFUL";
export const GET_TRACKER_BY_ID_ERROR = "GET_TRACKER_BY_ID_ERROR";

export const CREATE_TRACKER_LOG = "CREATE_TRACKER_LOG";
export const CREATE_TRACKER_LOG_SUCCESSFUL = "CREATE_TRACKER_LOG_SUCCESSFUL";
export const CREATE_TRACKER_LOG_ERROR = "CREATE_TRACKER_LOG_ERROR";

export const DELETE_TRACKER = "DELETE_TRACKER";
export const DELETE_TRACKER_SUCCESSFUL = "DELETE_TRACKER_SUCCESSFUL";
export const DELETE_TRACKER_ERROR = "DELETE_TRACKER_ERROR";
